### ISSUE TITLE
longpoll for Clever

### ISSUE THREAD

**Issue by TaizoGem** [TaizoGem/AKlever#8]

**Comment by oncecreated** [comment]
https://github.com/oncecreated/cleverapi

**Comment by TaizoGem** [comment]
огогого, ты как взломал хеш?

**Comment by oncecreated** [comment]
Ну это не взлом, конечно, но хэшируемые данные удалось получить путем реверс-инжиниринга нативной библиотеки.

**Comment by TaizoGem** [comment]
чем декомпилировал? _я пытался но у меня ничего_ не получилось

**Comment by oncecreated** [comment]
Нативную библиотеку анализировал идой.

**Comment by CoderOffka** [comment]
Ммм я как-то не заметил этого. Добавить бы возможность редактировать User-Agent в конфиге... А то все с Redmi Note 5 и версией клевера 2.3.3.. @oncecreated я твою библиотеку использовал для своего бота (для личного использования). Поменял версию клевера на свежую. Все event'ы пытался отправлять.. А потом нашел готовых ботов, а своего удалил. 

А идея была - выводить ~10 слов, где в поисковике встречаются ответы (выводить контекст использования ответа). И самому анализировать результат (а потом можно простенький ИИ натренировать..). Т.к. сейчас вопросы становятся более хитрыми, что-бы боты не находили верный ответ. Причем времени на анализ контекста очень много, примерно 7 секунд.

Я считал и считаю, что этот способ намного лучше, чем подсчитывать число вхождений ответа в результате поисковика. Но и просто открывать браузер - не вариант, т.к. много лишней информации + повторная загрузка страницы с картинками и прочей ерундой.
Спасибо за CleverApi @oncecreated, было весело :smile:
